#!/bin/sh

set -e

# Pass maintainer script parameters to hook scripts
export DEB_MAINT_PARAMS="$*"

# Tell initramfs builder whether it's wanted
export INITRD=Yes

test -d /etc/kernel/prerm.d && run-parts --arg="5.10.54-breath-alt" --arg="/boot/vmlinuz-5.10.54-breath-alt" /etc/kernel/prerm.d
exit 0
